export const serviceList = [
  {
    id: 1,
    title: "Corte de cabelo masculino",
    img: "./src/Assets/cards/corte.png",
    category: "Corte de cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo masculino",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 55.0,
  },
  {
    id: 2,
    title: "Corte de cabelo e barba",
    img: "./src/Assets/cards/corte.png",
    category: "Corte de cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo e barba",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 110.0,
  },
  {
    id: 3,
    title: "Pezinho Cabelo",
    img: "./src/Assets/cards/corte.png",
    category: "Corte de cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo masculino",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 15.0,
  },
  {
    id: 4,
    title: "Corte Cabelo Maquina",
    img: "./src/Assets/cards/corte.png",
    category: "Corte de cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo com maquina",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 40.0,
  },
  {
    id: 5,
    title: "Corte Infantil",
    img: "./src/Assets/cards/corte.png",
    category: "Corte de cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo infantil",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 55.0,
  },
  {
    id: 6,
    title: "Aplicação de Tintura",
    img: "./src/Assets/cards/corte.png",
    category: "Corte de cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Aplicação de tintura",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 70.0,
  },
  {
    id: 7,
    title: "Lavagem",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Lavagem de cabelo",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 20.0,
  },
  {
    id: 8,
    title: "Progressiva",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo masculino",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 85.0,
  },
  {
    id: 9,
    title: "Hidratação",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo com maquina",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 55.0,
  },
  {
    id: 10,
    title: "Relaxamento Capilar",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo infantil",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 75.0,
  },
  {
    id: 11,
    title: "Luzes",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Aplicação de tintura",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 0.0,
  },
  {
    id: 12,
    title: "Botox Capilar",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo infantil",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 65.0,
  },
  {
    id: 13,
    title: "Penteado",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Aplicação de tintura",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 35.0,
  },
  {
    id: 14,
    title: "Escova e finalização",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Aplicação de tintura",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 35.0,
  },
  {
    id: 15,
    title: "Coloração tonalização",
    img: "./src/Assets/cards/corte.png",
    category: "Cabelo",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Corte de cabelo infantil",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 50.0,
  },
  {
    id: 16,
    title: "Barboterapia",
    img: "./src/Assets/cards/corte.png",
    category: "Barba",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Aplicação de tintura",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 85.0,
  },
  {
    id: 17,
    title: "Barba",
    img: "./src/Assets/cards/corte.png",
    category: "Barba",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Aplicação de tintura",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 55.0,
  },
  {
    id: 18,
    title: "Depilação Barriga",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação de barriga",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 35.0,
  },
  {
    id: 19,
    title: "Depilação Peito",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação de peito",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 40.0,
  },
  {
    id: 20,
    title: "Depilação Nariz",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação de nariz",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 15.0,
  },
  {
    id: 21,
    title: "Depilação Buço",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação de buço",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 20.0,
  },
  {
    id: 22,
    title: "Depilação Costas",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação das costas",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 55.0,
  },
  {
    id: 23,
    title: "Depilação Axila",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação das axilas",
    longDescription:
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 30.0,
  },
  {
    id: 24,
    title: "Depilação Orelha",
    img: "./src/Assets/cards/corte.png",
    category: "Depilação",
    allImages: ["./src/Assets/cards/corte.png", "./src/Assets/cards/logo.jpg", "./src/Assets/cards/foto3.jpg"],
    description: "Depilação das orelhas",
    longDescription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero, expedita quasi magni ex, itaque sint reiciendis laboriosam eaque deleniti eoiste in? Eaque modi impedit itaque dolore aliquid corporis.",
    price: 15.0,
  },
];
